### ISSUE TITLE
IOS AppDelegate 설정

### ISSUE THREAD

**Issue by bumjin1013** [crossplatformkorea/react-native-naver-login#162]
### Description

#import <NaverThirdPartyLogin/NaverThirdPartyLoginConnection.h>
...

// 다른 URL 핸들링 로직이 없는경우
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
   return [[NaverThirdPartyLoginConnection getSharedInstance] application:app openURL:url options:options];
}

// 다른 URL 핸들링 로직이 같이 있는 경우
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  // naver
  if ([url.scheme isEqualToString:@"{{ CUSTOM URL SCHEME }}"]) {
    return [[NaverThirdPartyLoginConnection getSharedInstance] application:application openURL:url options:options];
  }
 //application:application -> application:app 으로 변경해야 build 됩니다.
  ...
}

### Steps to reproduce

application:application -> application:app 으로 변경해야 build 됩니다.

### Snack or a link to a repository

non

### React Native Naver Login version

3.0.0

### React Native version

0.70.6

### Platforms

iOS

### JavaScript runtime

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by jsh7195** [comment]
감사합니다

**Comment by mym0404** [comment]
제보 감사합니다. README.md 수정했습니다.
