### ISSUE TITLE
[iOS] 로그인 시도시 반응이 없습니다.

### ISSUE THREAD

**Issue by tree1891** [crossplatformkorea/react-native-naver-login#164]
### Description

NaverLogin.login 호출후 반응이 없습니다.

### Steps to reproduce

```
		const { successResponse } = await NaverLogin.login({
			appName: Config.NAVER_APP_NAME,
			consumerKey: Config.NAVER_CLIENT_ID,
			consumerSecret: Config.NAVER_CLIENT_SECRET,
                        serviceUrlScheme: Config.SERVICE_URL_SCHEME
		})
```

### Snack or a link to a repository

https://stackoverflow.com/help/mcve

### React Native Naver Login version

3.0.0-rc.1

### React Native version

0.70.7

### Platforms

iOS

### JavaScript runtime

None

### Architecture

None

### Build type

None

### Device

Real device

### Acknowledgements

Yes

**Comment by SayantaBhowmickDivii** [comment]
> 

I am facing the same issue.

**Comment by young-st511** [comment]
혹시 카카오 로그인 등과 같이 사용 중이시면 AppDelegate.mm 한번 확인해보세요!

**Comment by mym0404** [comment]
안녕하세요, 제보 감사합니다.

재현가능한 샘플을 부탁드리겠습니다.
