### ISSUE TITLE
android release build crash

### ISSUE THREAD

**Issue by koenzi132** [crossplatformkorea/react-native-naver-login#167]
### Description

안드로이드에서 release 빌드시 앱이 열리자마자 크래시가 나네요.
혹시 짐작가는 원인이 있으실까요
빌드는 성공되는데 앱이 열리자마자 닫혀서 원인 찾기가 어렵네요.
급하게 사용해야하는데 혹시 짐작가는 부분이 있으시다면 부탁드리겠습니다.

그래들 버전은 아래와 같습니다!
gradle-6.9-all (com.android.tools.build:gradle:3.6.0)

### Steps to reproduce

1. yarn add @react-native-seoul/naver-login
2. npx react-native run-android --variant=release
3. 앱 빌드 success -> 열리자마자 크래시

### Snack or a link to a repository

없음

### React Native Naver Login version

3.0.0-rc.2

### React Native version

0.63.4

### Platforms

Android

### JavaScript runtime

None

### Architecture

None

### Build type

None

### Device

Real device

### Acknowledgements

Yes

**Comment by DongGukMon** [comment]
이전에 쓰시다가 이번에 3.0.0-rc.2로 업그레이드 하신건가요?

**Comment by koenzi132** [comment]
이번에 처음 붙이는건데 3.0.0-rc2에서만 해당 증상이 발생하네요 (하위 버전들에서는 문제가 발생하지 않습니다!)

**Comment by koenzi132** [comment]
짐작 가시는 부분이 없으실까요?

**Comment by mym0404** [comment]
안녕하세요, 제보 감사드립니다.

우선, build variant를 release로 두고 실행해도 최신 버전의 Android Studio(Android Studio Iguana | 2023.2.1 Patch 1) logcat에는 크래시가 찍히는 것으로 보입니다.

이것으로 먼저 파악을 해보시고 혹시 재현가능한 샘플을 만들어주시면 감사하겠습니다.
