### ISSUE TITLE
Clarification Needed: Example App Fails to Run Until "file:.." Is Updated for NaverLoginExample

### ISSUE THREAD

**Issue by nomanoff** [crossplatformkorea/react-native-naver-login#171]
### Description

Hello,

I've recently forked the `NaverLoginExample` project to test the` @react-native-seoul/naver-login library` locally. During my testing, I've noticed an issue with the current setup of the example app that might be causing confusion for other developers.

Currently, when the example app is forked and the setup instructions are followed as per the documentation, it fails to run properly. This is due to the use of `"file:.."` in the `package.json` for the library. After making a change to the `package.json` and updating the `"file:.."` reference to a correct version like `"^3.0.0-rc.1"`, the example app starts working as expected.

I'd like to understand whether this behavior is intentional or if there might be an oversight in the setup instructions. My intention in reporting this issue is to ensure that other developers don't struggle unnecessarily when trying to run the example app locally 🤓

Thank you for the great work on this project, and I hope this feedback can contribute to a smoother onboarding experience for fellow developers ^^

### Steps to reproduce

1. Fork the NaverLoginExample project from the repository.

2. Follow the provided setup instructions in the documentation to set up the example app locally.

3. Attempt to run the example app as instructed.

### Snack or a link to a repository

https://github.com/nomanoff/react-native-naver-login

### React Native Naver Login version

^3.0.0-rc.1

### React Native version

0.70.3

### Platforms

iOS

### JavaScript runtime

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by mym0404** [comment]
Thank you for reporting.

Currently, the example project is deprecated and has to be reimplemented with a fresh setup.

In the recently RN community, it seems to that using `file:..` for example project configuration is not a working way.

If you create a library sample with cli like [create-react-native-library](https://www.npmjs.com/package/create-react-native-library), then you can see that example project even doesn't include parent package in `dependencies`.

With babel, metro, tsconfig, the original package source code is redirected into example project directly. This enable a cool feature that we can use `hot-reload` like experience within developing package.

**Comment by mym0404** [comment]
I rework on example project from #184.

It works as described above.

**Comment by nomanoff** [comment]
okay thanks
