### ISSUE TITLE
xcode 16에서 bitcode 오류로 동작이 되지 않습니다..

### ISSUE THREAD

**Issue by shleehyun** [crossplatformkorea/react-native-naver-login#200]
### Description

  native는 수정한것같은데 .. 여기도 수정을 해주세요 혹  좋은 방법있으면 알려주세요 ...

### Steps to reproduce

xcode 16에서 빌드해서 upload시에 오류가 납니다 bitcode 가 포함되어져 잇다고 ..

### Snack or a link to a repository

seunglee

### React Native Naver Login version

3.0.0

### React Native version

0.72,6

### Platforms

iOS

### JavaScript runtime

None

### Architecture

Fabric (New Architecture)

### Build type

Release mode

### Device

Real device

### Device model

iphone 15pro

### Acknowledgements

Yes

**Comment by rsuubinn** [comment]
저도 그 오류 생겼다가 라이브러리 버전을 ^4.0.0 으로 업데이트 하니 해결 됐습니다
다만 아이폰 16프로 iOS 18에서 네이버 로그인 시도하면 아무 반응이 없네요
login() 이 실행이 안되는거 같습니다

**Comment by parkdigy** [comment]
@rsuubinn iOS 18에서 아무 반응이 없는 경우는,
SDK가 금방 수정되서 업데이트 되겠지만, 급하시면 patch-package 를 이용하시면 됩니다.

node_modules/@react-native-seoul/naver-login/RNNaverLogin.podspec 파일에서

s.dependency 'naveridlogin-sdk-ios', '4.2.1'

이 부분의 버전을 4.2.3 으로 변경하고 pod update 하시면 됩니다.
테스트 해봤는데 iOS 18에서 잘 됩니다.

**Comment by mym0404** [comment]
Does #201 fix this? It was shipped in `4.0.2`

**Comment by RyuWoong** [comment]
4.0.2 버전으로 업데이트 후 App Store Upload시 문제가 없이 저는 잘 됩니다.
